# **Data Preprocessing for Delhivery Logistics Database.**

# **1. Load Dataset**

In [ ]:
import pandas as pd
import numpy as np

# Load the dataset into a DataFrame
df = pd.read_excel('Delivery Logistic_Data.xlsx')

## View First Few Rows

In [ ]:
df.head()

,data,trip_creation_time,route_schedule_uuid,route_type,trip_uuid,source_center,source_name,destination_center,destination_name,od_start_time,...,cutoff_timestamp,actual_distance_to_destination,actual_time,osrm_time,osrm_distance,factor,segment_actual_time,segment_osrm_time,segment_osrm_distance,segment_factor
0,training,2018-09-20 02:35:36.477,thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...,Carting,trip-153741093647649320,IND388121AAA,Anand_VUNagar_DC (Gujarat),IND388620AAB,Khambhat_MotvdDPP_D (Gujarat),2018-09-20 03:21:32.419,...,2018-09-20 04:27:55.000,10.435660,14,11,11.9653,1.272727,14,11,11.9653,1.272727
1,training,2018-09-20 02:35:36.477,thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...,Carting,trip-153741093647649320,IND388121AAA,Anand_VUNagar_DC (Gujarat),IND388620AAB,Khambhat_MotvdDPP_D (Gujarat),2018-09-20 03:21:32.419,...,2018-09-20 04:17:55.000,18.936842,24,20,21.7243,1.200000,10,9,9.7590,1.111111
2,training,2018-09-20 02:35:36.477,thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...,Carting,trip-153741093647649320,IND388121AAA,Anand_VUNagar_DC (Gujarat),IND388620AAB,Khambhat_MotvdDPP_D (Gujarat),2018-09-20 03:21:32.419,...,2018-09-20 04:01:19.506,27.637279,40,28,32.5395,1.428571,16,7,10.8152,2.285714
3,training,2018-09-20 02:35:36.477,thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...,Carting,trip-153741093647649320,IND388121AAA,Anand_VUNagar_DC (Gujarat),IND388620AAB,Khambhat_MotvdDPP_D (Gujarat),2018-09-20 03:21:32.419,...,2018-09-20 03:39:57.000,36.118028,62,40,45.5620,1.550000,21,12,13.0224,1.750000
4,training,2018-09-20 02:35:36.477,thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...,Carting,trip-153741093647649320,IND388121AAA,Anand_VUNagar_DC (Gujarat),IND388620AAB,Khambhat_MotvdDPP_D (Gujarat),2018-09-20 03:21:32.419,...,2018-09-20 03:33:55.000,39.386040,68,44,54.2181,1.545455,6,5,3.9153,1.200000

## Information about the number of non-null values in each column, data types, and memory usage.

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 144867 entries, 0 to 144866
Data columns (total 24 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   data                            144867 non-null  object
 1   trip_creation_time              144867 non-null  datetime64[ns]
 2   route_schedule_uuid             144867 non-null  object
 3   route_type                      144867 non-null  object
 4   trip_uuid                       144867 non-null  object
 5   source_center                   144867 non-null  object
 6   source_name                     144574 non-null  object
 7   destination_center              144867 non-null  object
 8   destination_name                144606 non-null  object
 9   od_start_time                   144867 non-null  datetime64[ns]
 10  od_end_time                     144867 non-null  datetime64[ns]
 11  start_scan_to_end_scan          144867 non-null  int64
 12  is_cutoff                       144867 non-null  bool
 13  cutoff_factor                   144867 non-null  int64
 14  cutoff_timestamp                144867 non-null  datetime64[ns]
 15  actual_distance_to_destination  144867 non-null  float64
 16  actual_time                     144867 non-null  int64
 17  osrm_time                       144867 non-null  int64
 18  osrm_distance                   144867 non-null  float64
 19  factor                          144867 non-null  float64
 20  segment_actual_time             144867 non-null  int64
 21  segment_osrm_time               144867 non-null  int64
 22  segment_osrm_distance           144867 non-null  float64
 23  segment_factor                  144867 non-null  float64
dtypes: bool(1), datetime64[ns](4), float64(5), int64(6), object(8)
memory usage: 25.6+ MB
None

## Missing values are present in each column

In [ ]:
print(df.isnull().sum())

data                                0
trip_creation_time                  0
route_schedule_uuid                 0
route_type                          0
trip_uuid                           0
source_center                       0
source_name                       293
destination_center                  0
destination_name                  261
od_start_time                       0
od_end_time                         0
start_scan_to_end_scan              0
is_cutoff                           0
cutoff_factor                       0
cutoff_timestamp                    0
actual_distance_to_destination      0
actual_time                         0
osrm_time                           0
osrm_distance                       0
factor                              0
segment_actual_time                 0
segment_osrm_time                   0
segment_osrm_distance               0
segment_factor                      0
dtype: int64

## Save the dataset in a structured format (CSV/Excel)

In [ ]:
# Save the DataFrame to an Excel file
df.to_excel('Delivery Logistic_Data.xlsx', index=False)

# **2. Handle Missing Values**

In [ ]:
missing_info = df.isnull().sum()
print("Missing Values in Each Column:")
print(missing_info[missing_info > 0])

Missing Values in Each Column:
source_name         293
destination_name    261
dtype: int64

## Define specific coloumn

In [ ]:
column_1 = 'source_name'
column_2 = 'destination_name'

## Droping rows where both columns have null values

In [ ]:
df.dropna(subset=[column_1, column_2], how='all', inplace=True)

## Filling missing values in each column individually

In [ ]:
df[column_1].fillna('missing', inplace=True)
df[column_2].fillna('missing', inplace=True)

## Recheck Missing Value after filling Missing value

In [ ]:
missing_info = df.isnull().sum()
print("Missing Values in Each Column:")
print(missing_info[missing_info > 0])

Missing Values in Each Column:
Series([], dtype: int64)

# **3. Correct Data Type**

## Display Data type of each coloumn

In [ ]:
df.dtypes

data                                      object
trip_creation_time                datetime64[ns]
route_schedule_uuid                       object
route_type                                object
trip_uuid                                 object
source_center                             object
source_name                               object
destination_center                        object
destination_name                          object
od_start_time                     datetime64[ns]
od_end_time                       datetime64[ns]
start_scan_to_end_scan                     int64
is_cutoff                                   bool
cutoff_factor                              int64
cutoff_timestamp                  datetime64[ns]
actual_distance_to_destination           float64
actual_time                                int64
osrm_time                                  int64
osrm_distance                            float64
factor                                   float64
segment_actual_time                        int64
segment_osrm_time                          int64
segment_osrm_distance                    float64
segment_factor                           float64
dtype: object

## Convert 'object' data type of 'route_type' coloumn to 'catagory' data type.

In [ ]:
df['route_type'] = df['route_type'].astype('category')

In [ ]:
df.dtypes

data                                      object
trip_creation_time                datetime64[ns]
route_schedule_uuid                       object
route_type                              category
trip_uuid                                 object
source_center                             object
source_name                               object
destination_center                        object
destination_name                          object
od_start_time                     datetime64[ns]
od_end_time                       datetime64[ns]
start_scan_to_end_scan                     int64
is_cutoff                                   bool
cutoff_factor                              int64
cutoff_timestamp                  datetime64[ns]
actual_distance_to_destination           float64
actual_time                                int64
osrm_time                                  int64
osrm_distance                            float64
factor                                   float64
segment_actual_time                        int64
segment_osrm_time                          int64
segment_osrm_distance                    float64
segment_factor                           float64
dtype: object

I found that other data type of coloumns are correct data type as per data so no need to change other data type.

# **4. Feature Engineering**

## Creating Trip Duration (in hours)

In [ ]:

df['trip_duration'] = (df['od_end_time'] - df['od_start_time']).dt.total_seconds() / 3600

In [ ]:
df['trip_duration']

0         1.436894
1         1.436894
2         1.436894
3         1.436894
4         1.436894
            ...
144862    7.128106
144863    7.128106
144864    7.128106
144865    7.128106
144866    7.128106
Name: trip_duration, Length: 144864, dtype: float64

## Finding days of the week and the month in the start time column for analyzing the time period

In [ ]:
df['day_of_week'] = df['od_start_time'].dt.day_name()
df['month'] = df['od_start_time'].dt.month

In [ ]:
df[["day_of_week","month"]]

       day_of_week  month
0         Thursday      9
1         Thursday      9
2         Thursday      9
3         Thursday      9
4         Thursday      9
...            ...    ...
144862    Thursday      9
144863    Thursday      9
144864    Thursday      9
144865    Thursday      9
144866    Thursday      9

[144864 rows x 2 columns]

In [ ]:
df.head()

,data,trip_creation_time,route_schedule_uuid,route_type,trip_uuid,source_center,source_name,destination_center,destination_name,od_start_time,...,osrm_time,osrm_distance,factor,segment_actual_time,segment_osrm_time,segment_osrm_distance,segment_factor,trip_duration,day_of_week,month
0,training,2018-09-20 02:35:36.477,thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...,Carting,trip-153741093647649320,IND388121AAA,Anand_VUNagar_DC (Gujarat),IND388620AAB,Khambhat_MotvdDPP_D (Gujarat),2018-09-20 03:21:32.419,...,11,11.9653,1.272727,14,11,11.9653,1.272727,1.436894,Thursday,9
1,training,2018-09-20 02:35:36.477,thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...,Carting,trip-153741093647649320,IND388121AAA,Anand_VUNagar_DC (Gujarat),IND388620AAB,Khambhat_MotvdDPP_D (Gujarat),2018-09-20 03:21:32.419,...,20,21.7243,1.200000,10,9,9.7590,1.111111,1.436894,Thursday,9
2,training,2018-09-20 02:35:36.477,thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...,Carting,trip-153741093647649320,IND388121AAA,Anand_VUNagar_DC (Gujarat),IND388620AAB,Khambhat_MotvdDPP_D (Gujarat),2018-09-20 03:21:32.419,...,28,32.5395,1.428571,16,7,10.8152,2.285714,1.436894,Thursday,9
3,training,2018-09-20 02:35:36.477,thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...,Carting,trip-153741093647649320,IND388121AAA,Anand_VUNagar_DC (Gujarat),IND388620AAB,Khambhat_MotvdDPP_D (Gujarat),2018-09-20 03:21:32.419,...,40,45.5620,1.550000,21,12,13.0224,1.750000,1.436894,Thursday,9
4,training,2018-09-20 02:35:36.477,thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...,Carting,trip-153741093647649320,IND388121AAA,Anand_VUNagar_DC (Gujarat),IND388620AAB,Khambhat_MotvdDPP_D (Gujarat),2018-09-20 03:21:32.419,...,44,54.2181,1.545455,6,5,3.9153,1.200000,1.436894,Thursday,9

# **5. Outlier Detection and Handling**

## Outlier in trip duration and delete that rows from the dataset

In [ ]:
Q1 = df['trip_duration'].quantile(0.25)
Q3 = df['trip_duration'].quantile(0.75)
IQR = Q3 - Q1
outlier_condition = (df['trip_duration'] < (Q1 - 1.5 * IQR)) | (df['trip_duration'] > (Q3 + 1.5 * IQR))

## Flaging outliers for further investigation

In [ ]:

df['trip_duration_outlier'] = np.where(outlier_condition, 'Yes', 'No')

In [ ]:
df['trip_duration_outlier']

0         No
1         No
2         No
3         No
4         No
          ..
144862    No
144863    No
144864    No
144865    No
144866    No
Name: trip_duration_outlier, Length: 144864, dtype: object

## Counting the occurrences of 'Yes' and 'No' in the 'trip_duration_outlier' column

In [ ]:
outlier_counts = df['trip_duration_outlier'].value_counts()

# Printing the counts
print(outlier_counts)

trip_duration_outlier
No     144491
Yes       373
Name: count, dtype: int64

## Removing rows where 'trip_duration_outlier' is "Yes"

In [ ]:
df = df[df['trip_duration_outlier'] == "No"].copy()

## Droping the 'trip_duration_outlier' column since it's no longer needed

In [ ]:
df.drop(columns=['trip_duration_outlier'], inplace=True)

## Verifying the shape of the cleaned DataFrame

In [ ]:
print("Number of rows and columns after removing outliers:", df.shape)

Number of rows and columns after removing outliers: (144491, 27)

In [ ]:
df.columns

Index(['data', 'trip_creation_time', 'route_schedule_uuid', 'route_type',
       'trip_uuid', 'source_center', 'source_name', 'destination_center',
       'destination_name', 'od_start_time', 'od_end_time',
       'start_scan_to_end_scan', 'is_cutoff', 'cutoff_factor',
       'cutoff_timestamp', 'actual_distance_to_destination', 'actual_time',
       'osrm_time', 'osrm_distance', 'factor', 'segment_actual_time',
       'segment_osrm_time', 'segment_osrm_distance', 'segment_factor',
       'trip_duration', 'day_of_week', 'month'],
      dtype='object')

In [ ]:
df.shape

(144494, 27)

# **6. Sanitize and Normalize Data**

## Standardize column names to follow a consistent format

In [ ]:
# Function to standardize column names
def standardize_column_names(df):
    # Create a mapping dictionary
    column_name_map = {}

    for col in df.columns:
        new_col = col.lower().replace(' ', '_').replace('(', '').replace(')', '')
        column_name_map[col] = new_col

    # Rename columns using the dictionary
    df = df.rename(columns=column_name_map)

    return df

# Apply the function to standardize column names
df_standardized = standardize_column_names(df)

print("Standardized Column Names:")
print(df_standardized.columns)

Standardized Column Names:
Index(['data', 'trip_creation_time', 'route_schedule_uuid', 'route_type',
       'trip_uuid', 'source_center', 'source_name', 'destination_center',
       'destination_name', 'od_start_time', 'od_end_time',
       'start_scan_to_end_scan', 'is_cutoff', 'cutoff_factor',
       'cutoff_timestamp', 'actual_distance_to_destination', 'actual_time',
       'osrm_time', 'osrm_distance', 'factor', 'segment_actual_time',
       'segment_osrm_time', 'segment_osrm_distance', 'segment_factor',
       'trip_duration', 'day_of_week', 'month'],
      dtype='object')

## Normalize numeric columns to a consistent scale for better analysis.

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

def normalize_min_max(df):
    # Initialize MinMaxScaler
    scaler = MinMaxScaler()

    # Apply scaling to numeric columns
    numeric_columns = df.select_dtypes(include=['int64', 'float64']).columns
    df[numeric_columns] = scaler.fit_transform(df[numeric_columns])

    return df

# Apply normalization to the DataFrame
df_normalized = normalize_min_max(df)

print("Normalized DataFrame:")
print(df_normalized.head())

Normalized DataFrame:
       data      trip_creation_time  \
0  training 2018-09-20 02:35:36.477
1  training 2018-09-20 02:35:36.477
2  training 2018-09-20 02:35:36.477
3  training 2018-09-20 02:35:36.477
4  training 2018-09-20 02:35:36.477

                                 route_schedule_uuid route_type  \
0  thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...    Carting
1  thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...    Carting
2  thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...    Carting
3  thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...    Carting
4  thanos::sroute:eb7bfc78-b351-4c0e-a951-fa3d5c3...    Carting

                 trip_uuid source_center                 source_name  \
0  trip-153741093647649320  IND388121AAA  Anand_VUNagar_DC (Gujarat)
1  trip-153741093647649320  IND388121AAA  Anand_VUNagar_DC (Gujarat)
2  trip-153741093647649320  IND388121AAA  Anand_VUNagar_DC (Gujarat)
3  trip-153741093647649320  IND388121AAA  Anand_VUNagar_DC (Gujarat)
4  trip-153741093647649320  IND388121AAA  Anand_VUNagar_DC (Gujarat)

  destination_center               destination_name           od_start_time  \
0       IND388620AAB  Khambhat_MotvdDPP_D (Gujarat) 2018-09-20 03:21:32.419
1       IND388620AAB  Khambhat_MotvdDPP_D (Gujarat) 2018-09-20 03:21:32.419
2       IND388620AAB  Khambhat_MotvdDPP_D (Gujarat) 2018-09-20 03:21:32.419
3       IND388620AAB  Khambhat_MotvdDPP_D (Gujarat) 2018-09-20 03:21:32.419
4       IND388620AAB  Khambhat_MotvdDPP_D (Gujarat) 2018-09-20 03:21:32.419

   ... osrm_time  osrm_distance    factor  segment_actual_time  \
0  ...  0.002976       0.001276  0.014613             0.078300
1  ...  0.008333       0.005488  0.013671             0.077086
2  ...  0.013095       0.010155  0.016630             0.078907
3  ...  0.020238       0.015775  0.018202             0.080425
4  ...  0.022619       0.019511  0.018143             0.075873

  segment_osrm_time  segment_osrm_distance  segment_factor  trip_duration  \
0          0.006828               0.005460        0.041354       0.017324
1          0.005587               0.004453        0.041084       0.017324
2          0.004345               0.004935        0.043049       0.017324
3          0.007449               0.005942        0.042153       0.017324
4          0.003104               0.001787        0.041233       0.017324

   day_of_week  month
0     Thursday      9
1     Thursday      9
2     Thursday      9
3     Thursday      9
4     Thursday      9

[5 rows x 27 columns]

# **7. Save Cleaned Data**

In [ ]:
df.to_excel('cleaned_logistics_data.xlsx', index=False)
print("Cleaned data saved successfully.")

Cleaned data saved successfully.

In [50]:
!apt-get install git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.11).
0 upgraded, 0 newly installed, 0 to remove and 49 not upgraded.